import Head from "next/head";
import Blogs from "../components/Blogs";
import Header from "../components/Header";

export default function Home({ blogs }) {
  return (
    <div className="md:w-9/12 w-11/12 mx-auto ">
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* blogs */}
      <Blogs blogs={blogs} />
    </div>
  );
}

export const getServerSideProps = async () => {
  const res = await fetch("https://fathomless-dawn-94067.herokuapp.com/blogs");
  const blogs = await res.json();

  return {
    props: {
      blogs,
    },
  };
};
